version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REDIS_HOST=redis://host.docker.internal
        - MYSQL_HOST=host.docker.internal
    ports:
      - 3333:3333
